services:
  - type: web
    name: aternos-bot
    env: python
    buildCommand: bash build.sh
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

